version: '3.8'
services:
  db:
    image: postgres:15
    container_name: acme-air-db
    environment:
      POSTGRES_DB: acmeair
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
