springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    # url: /openapi/acme-air.yaml  # Remove this line
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    info:
      title: Flight Booking API
      version: 1.0.0
      description: Contract-first API for searching and booking flights
    packages-to-scan: com.acme.air.controller
logging:
  level:
    root: INFO
    com.acme.air: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acmeair
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Pacific/Auckland
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
