spring doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /openapi/acme-air.yaml
    path: /swagger-ui.html
logging:
  level:
    root: INFO
    com.acme.air: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acmeair
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Pacific/Auckland
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
